### PR TITLE
Feature/date

### PR DESCRIPTION
**Pull request by tonytam-dinh**
date timestamp added + csv customer names file fixed

### CODE REVIEW

**Comment by ryanmcallistergrum** [comment]
Line 196: There should not be a space between the day and the T in the date string.

**Comment by ryanmcallistergrum** [comment]
Line 196: There should not be a space between the day and the T in the date string.

**Comment by ryanmcallistergrum** [comment]
Line 196: There should not be a space between the day and the T in the date string.

**Review by ryanmcallistergrum — CHANGES_REQUESTED** [review]
Line 196: There should not be a space between the day and the T in the date string.

**Review by ryanmcallistergrum — CHANGES_REQUESTED** [review]
randomGenerator, Line 157: Delete closing brace so rest of code is in object scope.

**Review by RevBMcK — APPROVED** [review]

**Review by ryanmcallistergrum — APPROVED** [review]
Looks good. Approved.

**Pull request merged**
